{
 "title": "APRS Telemetry",
 "time": { "from": "2023-10-12T14:08:59.000Z", "to": "2023-10-12T14:54:36.000Z" },
 "templating": {
  "list": [
   {
    "name": "Payload",
    "query": "{\"find\": \"terms\", \"field\":\"payload_callsign.keyword\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "APRS Telemetry Dashboard",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This is a generic dashboard to display telemetry from APRS, WSPR, and other slow (>1 min) update-rate balloon payloads."
   },
   "targets": [
    {
     "bucketAggs": [
      { "field": "datetime", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "datetime"
    }
   ]
  },
  {
   "title": "Reported Altitude",
   "type": "timeseries",
   "description": "Reported Altitude, in Metres",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "datetime", "id": "3", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "alt", "id": "4", "type": "avg" }
     ],
     "query": "payload_callsign.keyword : \"$Payload\" AND NOT sats:0",
     "timeField": "datetime"
    }
   ]
  },
  {
   "title": "Ascent / Descent Rate",
   "type": "timeseries",
   "description": "Ascent / Descent Rate; Calculated and Reported (if available)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "datetime", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "alt",
       "hide": false,
       "id": "1",
       "type": "avg"
      },
      {
       "field": "1",
       "hide": true,
       "id": "3",
       "type": "derivative"
      },
      {
       "id": "4",
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "3" }
       ],
       "settings": {
        "script": "params.var1/(($__interval_ms/1000))"
       },
       "type": "bucket_script"
      },
      { "field": "ascent_rate", "id": "5", "type": "avg" }
     ],
     "query": "payload_callsign.keyword : \"$Payload\" AND NOT sats:0",
     "timeField": "datetime"
    }
   ]
  },
  {
   "title": "Payload Environmental Sensor Data",
   "type": "timeseries",
   "description": "Data from payload environmental sensors (temperature, pressure, humidity), if available. Sensors with no data may report as zero.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "datetime", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "ext_humidity", "id": "1", "type": "avg" },
      { "field": "ext_pressure", "id": "3", "type": "avg" },
      { "field": "ext_temperature", "id": "4", "type": "avg" },
      { "field": "temp", "id": "5", "type": "avg" }
     ],
     "query": "payload_callsign.keyword : \"$Payload\"",
     "timeField": "datetime"
    }
   ]
  },
  {
   "title": "GNSS Satellites in Use",
   "type": "timeseries",
   "description": "The number of Global Navigation System (GPS, Glonass, Beidou, Galileo) satellites in use by the payload. Note that some HorusBinary payloads report the number of satellites + 100 or 200, depending on the power-save mode they are in.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "datetime", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "sats", "id": "1", "type": "avg" }
     ],
     "query": "payload_callsign.keyword : \"$Payload\"",
     "timeField": "datetime"
    }
   ]
  },
  {
   "title": "Map",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "datetime", "id": "7", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" },
      { "field": "position", "id": "1", "settings": { "precision": "7" }, "type": "geohash_grid" }
     ],
     "metrics": [
      { "field": "alt", "id": "6", "type": "avg" }
     ],
     "query": "payload_callsign.keyword : \"$Payload\" AND NOT sats:0 AND NOT lat:0",
     "timeField": "datetime"
    },
    {
     "bucketAggs": [
      { "field": "uploader_position", "id": "1", "settings": { "precision": "6" }, "type": "geohash_grid" },
      {
       "field": "uploader_callsign.keyword",
       "id": "12",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "alt", "id": "10", "type": "avg" }
     ],
     "query": "payload_callsign.keyword == \"$Payload\" AND NOT sats:0 AND NOT lat:0",
     "timeField": "datetime"
    }
   ]
  },
  {
   "title": "Signal-to-Noise Ratio",
   "type": "timeseries",
   "description": "Receiver-Reported Signal-to-Noise, for receiving software and modulations that support this (e.g. Horus-GUI, HorusDemodLib)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "uploader_callsign.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "100" },
       "type": "terms"
      },
      { "field": "datetime", "id": "3", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "snr", "id": "1", "type": "avg" }
     ],
     "query": "payload_callsign.keyword : \"$Payload\" AND snr:>-100",
     "timeField": "datetime"
    }
   ]
  },
  {
   "title": "Per-Receiver Packet Count",
   "type": "piechart",
   "description": "How many packets each receiver has uploaded over the currently selected time range.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "uploader_callsign.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "datetime", "id": "1", "type": "cardinality" }
     ],
     "query": "payload_callsign.keyword : \"$Payload\"",
     "timeField": "datetime"
    }
   ]
  },
  {
   "title": "Receiver-Reported Payload Transmit Frequency",
   "type": "timeseries",
   "description": "The payload transmit frequency, as reported by receiver stations. Note that not all software supports reporting this, and that the reported frequencies may be inaccurate due to receiver inaccuracies and drift.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "uploader_callsign.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "50" },
       "type": "terms"
      },
      { "field": "datetime", "id": "3", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "frequency", "id": "1", "type": "avg" }
     ],
     "query": "payload_callsign.keyword : \"$Payload\" AND frequency:<6000 AND frequency:>100",
     "timeField": "datetime"
    }
   ]
  },
  {
   "title": "Packet Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "uploader_callsign.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "100" },
       "type": "terms"
      },
      { "field": "datetime", "id": "3", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "payload_callsign.keyword : \"$Payload\"",
     "timeField": "datetime"
    }
   ]
  },
  {
   "title": "Voltages vs Temperature",
   "type": "timeseries",
   "description": "Shows the fairly common relationship between payload-reported voltages, and the payload temperature.\nNote that not all voltage metrics may be available on all payloads.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "datetime", "id": "3", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "batt", "id": "4", "type": "avg" },
      { "field": "temp", "id": "5", "type": "avg" },
      { "field": "solar_panel", "id": "6", "type": "avg" }
     ],
     "query": "payload_callsign.keyword : \"$Payload\"",
     "timeField": "datetime"
    }
   ]
  },
  {
   "title": "Export Data for current Time Range",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 47 },
   "options": {
    "content": "- [**Download KML**](https://api.v2.sondehub.org/amateur/telemetry/{{variable \"Payload\"}}?format=kml&datetime={{data.0.datetime }}&last={{toFixed data.0.durationS 0}})\n- [**Download CSV**](https://api.v2.sondehub.org/amateur/telemetry/{{variable \"Payload\"}}?format=csv&datetime={{data.0.datetime }}&last={{toFixed data.0.durationS 0}})\n- [**Download JSON**](https://api.v2.sondehub.org/amateur/telemetry/{{variable \"Payload\"}}?datetime={{data.0.datetime }}&last={{toFixed data.0.durationS 0}})\n\n**Note:** The CSV and JSON outputs include __all__ packets received by __all__ receivers, so are likely to contain duplicate entries and may also be out-of-order.\nFor the CSV output in particular, it's recommended to sort the datetime field in ascending order before working with the data."
   },
   "targets": [
    {
     "bucketAggs": [
      { "field": "datetime", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "datetime", "id": "1", "type": "max" },
      { "field": "datetime", "id": "3", "type": "min" }
     ],
     "timeField": "datetime"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "datetime", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "payload_callsign.keyword : \"$Payload\"",
     "timeField": "datetime"
    }
   ]
  }
 ]
}